Выполнены задачи лекции 3
js-tasks-ru/js-20211109_919869 pull request #3
Opened 2021-11-19 06:53 UTC by 919869

2021-11-19 06:55 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-11-19 16:22 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const keys = path.split('.').reverse();
👍 лайк за использование замыкания

2021-11-19 16:22 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        let result = null;
здесь не нужно присваивать `null`, можно просто объявить `let result;`

2021-11-19 16:22 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    function getKeyValue(keys, obj) {
👍 лайк за рекурсию

2021-11-19 16:26 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        const currKey = keys.pop();
вот тут опасный момент: Вы мутируете `keys` значение которое доступно в родительской функции, другими словами вот в такой ситуации будет некорректный результат:
```
const g1 = createGetter('foo.bar');
const g2 = createGetter('baz.zoo');

g1({ foo: { bar: 2 } });
```
после такого вызова в `g2` уже будет некорректное значение `keys`

2021-11-19 16:27 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    const invertMap = new Map();
`Map` здесь можно использовать, но стоит ли делать это ради просто вызова метода `set`?

2021-11-19 16:27 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +    let count = 0;
good 👍

2021-11-19 16:28 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +    return Array.from(new Set(arr));
подумайте какие есть преимущества у `Array.from` по сравнению с спред-синтаксисом:
```
return [...new Set(arr)]
```

2021-11-19 16:28 UTC, dosandk requested changes
решение `createGetter` следует поправить

2021-11-28 14:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-11-28 14:53 UTC, 919869 commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +    return Array.from(new Set(arr));
Array.from позволяет вызывать дополнительную логику в функции

2021-11-28 18:20 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    let result = {}
`const`

2021-11-28 18:20 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const pathArray = path.split('.');
👍 good

2021-11-28 18:20 UTC, dosandk approved these changes
good 👍

2021-11-28 18:21 UTC, merged